### ISSUE TITLE
Unable to block IP

### ISSUE THREAD

**Issue by kalkrishnan** [gotthardp/rabbitmq-auth-backend-ip-range#10]
I am a little confused about the usage of this plugin. I read in the documentation that it should only be used for authorization and not authentication, but I also read the below:

"This will allow users with the tag ip-private to login from private networks only. Other users will be able to login from any network."

The above seems like it would block authentication from IP addresses as well. My config is as below:

`[
  {rabbit, [
        {auth_backends, [{rabbit_auth_backend_internal,
                      [rabbit_auth_backend_internal, rabbit_auth_backend_ip_range]
        }]},{loopback_users, [test]}
    ]},
    {rabbitmq_auth_backend_ip_range, [
        {tag_masks,
            [{'test', [<<"::FFFF:192.168.30.156">>]}]
        }
  ]}
].`

Based on this, any user tagged with test should only be able to login if accessing from the IP: 192.168.30.156. This doesn't seem to be true as we are able to access and login from other servers.

**Comment by lukebakken** [comment]
Please carefully re-read the examples for `tag_masks`. They appear to require a netmask. In your case, the following should work:

```
<<"::FFFF:192.168.30.156/255">>
```

If it does not, please follow up. Thanks.
