### ISSUE TITLE
Please provide an example to configure the plugin with new Configuration format

### ISSUE THREAD

**Issue by rozaydin** [gotthardp/rabbitmq-auth-backend-ip-range#11]
Can you provide an example that uses new config format for the plugin ?

**Comment by lukebakken** [comment]
The new format is not yet supported by this community plugin. If you're having problems using `rabbitmq.conf` (the new style) along with `advanced.config` (where settings for this plugin would go), please ask a question on the [`rabbitmq-users`](https://groups.google.com/forum/#!forum/rabbitmq-users) mailing list. Thanks
