### ISSUE TITLE
New releases for 3.6.16 and 3.7.13

### ISSUE THREAD

**Issue by lhriley** [gotthardp/rabbitmq-auth-backend-ip-range#14]
On the https://github.com/gotthardp/rabbitmq-auth-backend-ip-range/releases page, the last release is `v0.2.0` in Dec. 2015. This release does not contain a pre-built `.ez` file, unlike the `v0.1.1` release (https://github.com/gotthardp/rabbitmq-auth-backend-ip-range/releases/download/v0.1.1/rabbitmq_auth_backend_ip_range-0.1.1-rmq3.5.6.ez).

Since the `v0.2.0` release there has been at least one additional version bump (`v3.0.7`) according to the history listed in `README.md`:

```
3.7.0 (August 1, 2018). Compatible with RabbitMQ 3.7.x.
0.2.0 (Dec 22, 2015). Compatible with RabbitMQ 3.6.x.
Implement RabbitMQ Issue 109 fix for authorization of MQTT/STOMP connections.
0.1.1 (Oct 27, 2015) Bugfix release.
IPv4-mapped IPv6 addresses now match the respective IPv4 address.
Added some debug logs to hunt the Issue #2.
Authenticate against remote (client) address instead of local (server) address.
0.1.0 (Nov 14, 2014) First release. Compatible with RabbitMQ 3.5.x only.
```

Example:

```
v0.2.0
@gotthardp gotthardp released this on Dec 22, 2015 · 20 commits to master since this release

Implement RabbitMQ Issue 109
Compatibility changes for RabbitMQ 3.6.x
Assets 2
Source code (zip)
Source code (tar.gz)
```

To make this plugin more accessible, it would make sense to produce binary distributions in `.ez` format rather than leave this task to the user.

**Comment by michaelklishin** [comment]
Looks like I have the permissions to produce a new release. It will take some time to test/adapt before we can produce one but it's realistic to have something ready in the next week or so.

**Comment by michaelklishin** [comment]
Worth mentioning: master now contains a 3.8-specific API change, so PRs and releases for 3.7 should use the`v3.7.x` branch.

**Comment by michaelklishin** [comment]
I produced a release for [3.7.14](https://github.com/gotthardp/rabbitmq-auth-backend-ip-range/releases/tag/v3.7.14).

RabbitMQ 3.6.x has been out of support for almost 1 year now, without significant interest from the community we will pass on doing any more work on 3.6.x community plugins.
