### ISSUE TITLE
"unknown" peer host value not taken into account

### ISSUE THREAD

**Issue by lukebakken** [gotthardp/rabbitmq-auth-backend-ip-range#18]
Reported here: [comment](https://github.com/gotthardp/rabbitmq-auth-backend-ip-range/issues/6#issuecomment-545443133)

**Comment by lukebakken** [comment]
@arozhentsev I can reproduce this and don't have to use IPv6. I'll have a fix soon.

**Comment by arozhentsev** [comment]
Hello, everyone!
I rebuild plugin with new code that you put in the pull request and all work like a charm!
Waiting for merge to master. Thanks!

**Comment by lukebakken** [comment]
Thanks for the report

**Comment by lukebakken** [comment]
@arozhentsev please use the `v2.0.0` release you can find here:

https://github.com/gotthardp/rabbitmq-auth-backend-ip-range/releases/tag/v2.0.0

Thanks for testing for us.
