### ISSUE TITLE
Is it possible to use IP authz combined with internal authz

### ISSUE THREAD

**Issue by moldyseaswimmer** [gotthardp/rabbitmq-auth-backend-ip-range#20]
This doesn't appear to work:
auth_backends.1.authn = ldap
auth_backends.1.authz = rabbit_auth_backend_ip_range
auth_backends.2.authz = internal

I get not a management user in logs - I guess it is not checking the internal db

advanced.config looks like this:
[
{rabbitmq_auth_backend_ip_range, [
    {tag_masks,
        [{'dotnetclient', [<<"::FFFF:192.168.0.0/112">>]}]},
    {default_masks, [<<"::0/127">>]}
]}
].

**Comment by lukebakken** [comment]
In the future please ask questions on the mailing list where more people will see it, assist you, and learn from it -

https://groups.google.com/forum/#!forum/rabbitmq-users

Please re-read the documentation here -

https://github.com/gotthardp/rabbitmq-auth-backend-ip-range#setup-the-access-control-list

Put the `internal` `authz` setting _before_ `rabbit_auth_backend_ip_range`. The `tag_masks` setting takes a tagged user and decides if it should be authorized based on the user's IP address. In your case, the users must be assigned the `management` tag by either the `ldap` or `internal` backend first. In addition, your settings only allow users with the tag `dotnetclient` to log in. Your `default_masks` setting blocks all other tags / IP addresses.
