### ISSUE TITLE
Heads-up: RabbitMQ 3.7.0 authz behaviour changes

### ISSUE THREAD

**Issue by michaelklishin** [gotthardp/rabbitmq-auth-backend-ip-range#4]
This is not really an issue but a heads-up: in 3.7.0, we've added a couple new functions to the authorization backend behaviour, see https://github.com/rabbitmq/rabbitmq-server/issues/505 and https://github.com/rabbitmq/rabbitmq-server/issues/1085.

**Comment by uvzubovs** [comment]
Will you be publishing a white paper or a guide on how to use and what is supported with topic authorizations?
